src/postgres.c

\u0000 is an invalid sequence
instead of trying to insert, we will just log it and throw it away

Don't try to insert invalid lines

---

src/main.c
src/utils/helper.c
src/utils/helper.h

Use c11 atomic booleans with read-modify-write and load operations to
prevent data races due to concurrent access to run and ready states.
This fixes the three main potential data races reported by helgrind. See
the referenced issue for more context on the races.
In addition the commit modifies state names for clarity.
Fixes: #19

use c11 atomics for lockless state tracking w/o races

---

src/utils/logger.c

POSIX.1-2008 marks asctime (which is MT-Unsafe) as obsolete.
Use strftime() for buffer_set_timestamp() which saves an additional
snprintf() and simplifies bounds checking.

Logger replace asctime with strftime

---

src/main.c

The signal handler requires an initialised logger so it's optimal to drop the second call rather than the first one.

logger: drop needless reinitialisation

---

src/utils/logger.c
src/utils/logger.h

WIP: This needs a bit more testing. I have only briefly tested it so far and it fixed the issue.
Hence in progress.
Running schaufel under helgrind reports a potential data race
due to concurrent writes to the log buffer:
```
==22079== Possible data race during write of size 1 at 0x6954388 by thread #4
==22079== Locks held: none
==22079==    at 0x4C38DCC: mempcpy (vg_replace_strmem.c:1517)
==22079==    by 0x57B0C35: _IO_default_xsputn (in /usr/x86_64-pc-linux-gnu/lib/libc-2.27.so)
==22079==    by 0x5784D24: vfprintf (in /usr/x86_64-pc-linux-gnu/lib/libc-2.27.so)
==22079==    by 0x57ABFCF: vsnprintf (in /usr/x86_64-pc-linux-gnu/lib/libc-2.27.so)
==22079==    by 0x578BC06: snprintf (in /usr/x86_64-pc-linux-gnu/lib/libc-2.27.so)
==22079==    by 0x406211: buffer_set_timestamp (logger.c:43) …
```

use a thread local buffer for logging

---

Makefile
src/main.c
src/version.h

Fixes: #28 
Version is defined via Makefile and passed at compile time.
I'm by no means keen on this approach, can make it any way you like.

introduced versioning, set version to 0.1

---

src/kafka.c
src/main.c
src/queue.c
src/queue.h

Messages are blobs, not strings.
This PR aims to fix this problem by extending the data structure of message by datalen.
It's required for using schaufel as an interconnect between kafka clusters (multidc).

Kafka consume memcpy

---

src/file.c
src/postgres.c
src/redis.c

The aim of this pull request is to handle binary data everywhere (as we can now have binary data).
For postgres (bagger), this means that we only check whether we can assume our data can be handled as a string. All other possible errors are left to postgres's input validator.

Producer datalen

---

src/utils/logger.c

Since len's last byte is always a '\0', we don't want to write that, ever.
Now we could just not terminate log_buffer, but for future usage I'd like it to be a terminated string.

logger.c: fix off by one in logger_write

---

src/postgres.c
src/postgres.h

The postgres producer (which will soon be renamed bagger producer) doesn't end copy unless there are 2000 entries reached.
This generates three problems:
- the data table in a schema may not be altered until copy end (I mostly avoid this problem already with some extra sql)
- data appears with hours of delay in some cases
- in case of a dead database handle, it also crashes with hours of delay

Commit intervals

---

src/postgres.c

This race is ultra-rare (can't be reproduced with millions of inserts). That means with our workload, we hit it every other hour.
It causes the postgres connection to go out of sync, because one might put copy messages while copy is being finished.

postgres.c: avoid race condition on m->copy

---

src/kafka.c

Turns out we did create a memory leak after all.
I rearranged the code so that rkmessage is destroyed if you leave the case statement.

src/kafka.c: destroy all rdkafka error messages

---

Makefile
debug.sh
scripts/debug.sh
t/file_consumer_test.c
t/queue_test.c

The old makefile ignored system defined compilers,linkers, CFLAGS and always installed debug schaufel.
This means every bin package has been created without optimization for cpu architecture and without any optimization flags.
I've therefore removed the entire debug codepath in our makefile and rather made CFLAGS definable by environment.
The function of the debug codepath is now rather delegated to debug.sh which simply calls the makefile with appropriate debug flags.

Makefile: removed debug, moved functionality to debug.sh

---

Makefile

This allows us to fix the ebuild and solve https://github.com/adjust/gentoo-overlay/issues/194

Makefile: support for destdir/bindir env variables

---

Makefile
src/exports.c
src/queue.c
src/queue.h
src/utils/endian.h
src/utils/postgres.c

These are the only cases I noticed where includes break on non glibc machines.
I didn't check out whether all source files are reasonably self contained, that's for the next version of schaufel.

{exports,queue}.c: added headers for standard conforming libcs

---

src/postgres.c

This PR transforms `.` to `_`, so fqdns can be compatible with postgres schemas.

src/postgres.c: cpycmd support for fqdns

---

src/exports.c

The implementation of gregorian calendar weirdness should be correct now.

src/exports.c: fix date calculation from august on

---

man/schaufel.conf.5
src/exports.c

To move https://github.com/adjust/data-science/issues/816 along, I've implemented filtering on json data. Data can be now stored or discarded if certain conditions are met.
The semantics of functionality are described in schaufel.conf.5.
In the long run, this PR lays the framework to deprecate gin indexes in bagger.

Exports filters

---

Makefile
man/schaufel.conf.5
src/kafka.c
src/main.c
src/postgres.c
src/utils/config.c
src/utils/config.h
src/utils/scalloc.c
src/utils/scalloc.h

Here is the first approach to the problem of setting defaults to the data providers. Three new functions were introduced to manipulate configs:
```c
config_setting_t *config_create_path(config_setting_t *parent,
const char *path,
int type)
```
Create a new setting node using the provided `path`. The path is specified as a string in form of `"path/to/my/setting"` (i.e. a slash separated list of nested setting groups). If path doesn't exist the function will automatically create all the nodes. If it does then the function returns `NULL`.
```c
void config_set_default_string(config_setting_t *parent,
const char *path,
const char *value)
```
Creates a new string setting node and sets a value to it. Again if setting doesn't exists then function returns a pointer to the created setting; …

Default options for kafka and postgres providers

---

src/kafka.c

Having this information helps narrowing down the problematic kafka host.

Log partition of the failed write request to Kafka

---

Makefile

Some distributions install Postgres headers into non standard directory. For example, Ubuntu installs it in the directory "/usr/include/postgresql".
This directory can be retrieved by using `pg_config`:
```
$ pg_config --includedir
/usr/include/postgresql
```
In this case it is necessary to include it explicitly.

Use pg_config to use postgres include dirs

---

man/schaufel.1
man/schaufel.conf.5
src/kafka.c
t/config_test.c

Librdkafka has warned about the per topic commit api being deprecated for a while, and with api v2 it is going dropped.
Luckily the change required to switch to the global commit api is miniscule. I've taken the liberty of adding test cases for the involved src/config/config.c functions.
Furthermore, I've removed the useless producer callback from kafka_consumer_meta_init. rdkafka now initialises without warnings.
fix: #61

rdkafka offset commit api

---

src/utils/logger.c

Log file is created with `0640` permissions so it is unreadable by schaufel monitoring scripts. I would like to give `others` permission to read a file.

logger.c: make log readable by monitoring scripts

---

doc/dummy.conf
man/schaufel.1
man/schaufel.conf.5
src/utils/config.c
src/utils/config.h
src/utils/logger.c
src/utils/logger.h
src/utils/strlwr.c
src/utils/strlwr.h
t/file_consumer_test.c
t/logger_test.c
t/logparse_test.c
t/strlwr_test.c

The logger not supporting file modes, not having a sane default, not supporting syslog, etc.pp. have all been troublesome.
This PR extends the logger with some basic functionality. More importantly, it makes the logger default to stderr.

Logger rework

---

src/utils/logger.c

On glibc, syslog.h expects the first argument to be a format.
Autor:           Ildus Kurbangaliev <i.kurbangaliev@gmail.com>
Date:            Mon Dec 13 21:34:13 2021 +0500

utils/logger.c: use gnu definition of syslog (with format)

---

src/postgres.c

gcc11s pedantic warnings do not like an empty fallthrough case.
Since we just want to jump to default, removing this case fixes the warning.
Author:           Ildus Kurbangaliev <i.kurbangaliev@gmail.com>
Date:             Wed Dec 15 07:02:48 2021 +0100

src/postgres.c: fix gcc11 empty statement case warning

---

src/kafka.c
src/kafka.h

Work in progress.
This new consumer mode allows to consume specific kafka partitions.
The syntax is like this:
```
schaufel -i k -b kafka.broker.local -t topic.name.kind:0-15,20,25
```
The simple consumer will disable offset storage.
I haven't implemented the simple producer yet.

Kafka simple consumer and per partition assignment.

---

src/utils/logger.c

Freebsd doesn't expect fcntl.h to define S_ISUID & co. There's no harm in including sys/types.h unconditionally.

Freebsd portability

---

src/exports.c
src/hooks/jsonexport.c

This is a funny one. The analyzer only finds this condition when building with O2.
(cherry picked from commit 66b7ef9df0a8fc34dc224b4b7882f767584e960d)

src/exports.c,src/hooks/jsonexport.c: fix uninitialised variable warning

---

t/dummy_consumer_test.c

This test has had missing curly braces and didn't error out since 2017.
Fixed.

t/dummy_consumer_test.c: fix indentation and error path

---

src/file.c

Fixes: #107
Before:
```
% ./schaufel -c1 -p1 -if -of
Thu Nov 24 09:45:20 2022 logger initialized
Thu Nov 24 09:45:20 2022 file.c 27: (null) Bad address
zsh: abort (core dumped)  ./schaufel -c1 -p1 -if -of
```
After:
```
% ./schaufel -c1 -p1 -if -of
file consumer/producer needs a valid filename!
file consumer/producer needs a valid filename!
usage
...
```

file: warn & exit on filename not given

---

src/file.c

Before:
```
% yes | ./schaufel -c1 -p1 -if -of -f/dev/stdin -F/dev/full
Mon Nov 21 15:37:54 2022 logger initialized
Mon Nov 21 15:37:54 2022 waiting for producer to come up
Mon Nov 21 15:37:55 2022 producer are up
Mon Nov 21 15:37:59 2022 added / s: 0 delivered / s: 0
Mon Nov 21 15:38:04 2022 added / s: 1081091 delivered / s: 1081091
Mon Nov 21 15:38:09 2022 added / s: 1507214 delivered / s: 1507214
Mon Nov 21 15:38:14 2022 added / s: 1378029 delivered / s: 1378029
Mon Nov 21 15:38:19 2022 added / s: 1382260 delivered / s: 1382041
Mon Nov 21 15:38:24 2022 added / s: 1316295 delivered / s: 1316514
^CMon Nov 21 15:38:26 2022 received signal to stop
Mon Nov 21 15:38:29 2022 added / s: 1209423 delivered / s: 1209423
Mon Nov 21 15:38:36 2022 file.c 37: No space left on device
Mon Nov 21 …
```

file: abort early on error in file producer

---

.github/workflows/build-package.yml
.github/workflows/test-pr.yml
Makefile
debian/control

- Updated package's dependencies for Ubuntu Jammy and Noble releases
- Added Ubuntu Jammy and Noble to GitHub actions, both testing and release packages
- Updated FreeBSD actions release

debian/control: Updated dependencies from Ubuntu Jammy and Noble

---

ChangeLog
Makefile
configure.ac
debian/control

- Release https://github.com/adjust/schaufel/pull/121

Release v0.11.1
